### ISSUE TITLE
jpegBytes

### ISSUE THREAD

**Issue by mbenci** [omarhurani/flutter_painter#4]
Just as it is possible to obtain an image in png format (using the pngBytes extension) it would be useful to have it also in jpeg format, for example when the starting image is a jpeg.

**Comment by omarhurani** [comment]
This getter uses Flutter's [ImageByteFormat](https://api.flutter.dev/flutter/dart-ui/ImageByteFormat-class.html) format enumeration which currently only contains `png`, `rawRgba` and `rawUnmodified`, so JPEG is not supported by default. With these, I can add getters for the raw bytes and unmodified bytes (which can represent JPEG if the original image is JPEG). However, these isn't an explicit way to covert an image into a JPEG from any format using Dart and Flutter without using external dependencies, which I am avoiding because it can cause conflicts in projects. You can use the [image](https://pub.dev/packages/image) package to do conversions between multiple types of images.
